// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NtaraFootballTest.Api.Database;

#nullable disable

namespace NtaraFootballTest.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240806153326_UpdatedFootballTeams")]
    partial class UpdatedFootballTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("NtaraFootballTest.Api.Entities.FootballTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DateOfLastWin")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Games")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mascot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ties")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WinningPercentage")
                        .HasColumnType("REAL");

                    b.Property<int?>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FootballTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
